import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import { Toaster } from '@/components/ui/Toaster/Toaster';
import AuthProvider from '@/providers/AuthProvider/AuthProvider';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import ReactQueryProvider from '@/providers/ReactQueryProvider/ReactQueryProvider';

// TODO: This is temporary until we have a better solution
export const dynamic = 'force-dynamic';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props extends PropsWithChildren {}

async function RootLayout({ children }: Props) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html className='h-full' lang='en'>
      <body className={cn(inter.className, 'h-full')}>
        <ReactQueryProvider>
          <AuthProvider accessToken={accessToken}>
            {children}
            <Toaster />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;
