import { PropsWithChildren } from 'react';
import './globals.css';

import RootLayout from '@/layouts/RootLayout/RootLayout';
import { Metadata } from 'next';

// TODO: This is temporary until we have a better solution
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props extends PropsWithChildren {}

function Layout({ children }: Props) {
  return <RootLayout>{children}</RootLayout>;
}

export default Layout;
